### ISSUE TITLE
sinon-chrome support

### ISSUE THREAD

**Issue by errorx666** [tfoxy/chrome-promise#16]
Edit:
I see your unit test is using `sinon-chrome`, but for me it doesn't populate e.g. `chromep.storage.local`.  Stepping through the debugger, the `hasOwnProperty` check in `fillProperties` returns `false` for this property.

**Comment by tfoxy** [comment]
This is because of the way properties are defined in `sinon-chrome`.

If I run `Object.getOwnPropertyDescriptor(chrome.tabs, 'create')`:

* With chrome extension: `{writable: true, enumerable: true, configurable: true, value: function}`
* With `sinon-chrome`: `{get: function, set: undefined, enumerable: false, configurable: false}`

I think it's better to fix this in `sinon-chrome` repo. Can you create an issue?

**Comment by tfoxy** [comment]
I made a PR in sinon-chrome

https://github.com/acvetkov/sinon-chrome/pull/77

So I'm closing this.
